//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziBlogProje.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BLOG()
        {
            this.TBL_YORUM = new HashSet<TBL_YORUM>();
        }
    
        public int BlogId { get; set; }
        public string BlogBaslik { get; set; }
        public string BlogIcerik { get; set; }
        public Nullable<System.DateTime> BlogTarih { get; set; }
        public Nullable<byte> BlogTur { get; set; }
        public Nullable<byte> BlogKategori { get; set; }
        public string BlogGorsel { get; set; }
    
        public virtual TBL_KATEGORI TBL_KATEGORI { get; set; }
        public virtual TBL_TUR TBL_TUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_YORUM> TBL_YORUM { get; set; }
    }
}
