//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziBlogProje.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YORUM
    {
        public int YorumId { get; set; }
        public string KullaniciAdi { get; set; }
        public string Mail { get; set; }
        public string Yorumİcerik { get; set; }
        public Nullable<int> YorumBlog { get; set; }
    
        public virtual TBL_BLOG TBL_BLOG { get; set; }
    }
}
